# Generated by Django 4.1.7 on 2023-04-28 04:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0004_remove_category_subscribers_category_subscribe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='subscribe',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
